current progress
Nuclearl/book_store pull request #2
Opened 2021-08-25 20:32 UTC by Nuclearl

https://drive.google.com/drive/folders/0B3jvg6jQR0D9QlV3RjducDEta3M?resourcekey=0-adUUXDhvH0f4BJ_sh7r3UQ

2021-08-30 09:31 UTC, WoLkErSs requested changes
Move all text to I18n

2021-08-30 09:31 UTC, WoLkErSs commented on app/models/book.rb
> +    errors.add(:images, 'is too many') if images.size > NUMBER_PHOTOS
I18n

2021-08-30 09:31 UTC, WoLkErSs commented on app/models/book.rb
> +  has_many :books_sections, dependent: :destroy
rename to categories

2021-08-30 09:31 UTC, WoLkErSs commented on app/models/book.rb
> +  NUMBER_PHOTOS = 4
move under class name

2021-08-30 09:31 UTC, WoLkErSs commented on app/models/section.rb
> +class Section < ApplicationRecord
rename to category

2021-08-30 09:31 UTC, WoLkErSs commented on app/models/user.rb
> +class User < ApplicationRecord
use VCR to test it

2021-08-30 09:31 UTC, WoLkErSs commented on app/services/books_services/filters.rb
> +      super()
remove

2021-08-30 09:31 UTC, WoLkErSs commented on app/services/books_services/filters.rb
> +        Book.all
have to returne books
add specs on this case

2021-08-30 09:31 UTC, WoLkErSs commented on app/services/books_services/filters.rb
> +      books = receive_books_from_sections(section)
do not use words like `receive` or `get` in method name

2021-08-30 09:31 UTC, WoLkErSs commented on spec/controllers/address_controller_spec.rb
> +require 'rails_helper'
remove

2021-08-31 09:15 UTC, Nuclearl commented
https://drive.google.com/drive/folders/0B3jvg6jQR0D9QlV3RjducDEta3M?resourcekey=0-adUUXDhvH0f4BJ_sh7r3UQ

2021-08-31 09:50 UTC, WoLkErSs requested changes

2021-08-31 09:50 UTC, WoLkErSs commented on config/environments/production.rb
> +    :domain => 'blooming-river-38869.herokuapp.com',
move to credentials

2021-08-31 09:50 UTC, WoLkErSs commented on config/environments/test.rb
> +  config.eager_load = true
read about eager_load, please

2021-08-31 09:50 UTC, WoLkErSs commented on spec/controllers/address_controller_spec.rb
> +      it { is_expected.to respond_with(200) }
check current page

2021-08-31 09:50 UTC, WoLkErSs commented on spec/controllers/books_controller_spec.rb
> +      my_services = instance_double('Filters')
move to let

2021-08-31 09:50 UTC, WoLkErSs commented on spec/controllers/books_controller_spec.rb
> +      my_services = instance_double('Filters')
use Constant not string

2021-08-31 09:50 UTC, WoLkErSs commented on spec/controllers/review_controller_spec.rb
> +      it { expect(Review.all.size).to eq 1 }
use change by

2021-08-31 09:50 UTC, WoLkErSs commented on spec/controllers/settings_controller_spec.rb
> +    it { expect(user.addresses.size).to eq 2 }
you have to check exactly type of addresses

2021-08-31 09:50 UTC, WoLkErSs commented on spec/controllers/settings_controller_spec.rb
> +    it { expect(user.destroy).to be_truthy }
validate that amount changed by 1

2021-08-31 09:50 UTC, WoLkErSs commented on spec/controllers/welcome_controller_spec.rb
> +    it { expect(assigns[:latest_books].size).to eq 3 }
use constant

2021-08-31 09:50 UTC, WoLkErSs commented on spec/controllers/welcome_controller_spec.rb
> +    it { expect(assigns[:latest_books]).to be_instance_of Array }
check what inside array

2021-08-31 09:50 UTC, WoLkErSs commented on spec/factories/books.rb
> +      4.times do
do not save 4 photos, 1 will be enough

2021-08-31 09:50 UTC, WoLkErSs commented on spec/features/authentication/forgot_password_spec.rb
> +  let(:user) { FactoryBot.create(:user, email: 'test@test.com') }
use ffaker

2021-08-31 09:50 UTC, WoLkErSs commented on spec/features/authentication/restore_password_spec.rb
> +  context 'when change password if url is incorrect' do
rename

2021-08-31 09:50 UTC, WoLkErSs commented on spec/features/authentication/restore_password_spec.rb
> +  context 'when change password if url is incorrect' do
add test when invalid token

2021-08-31 09:50 UTC, WoLkErSs commented on spec/features/authentication/restore_password_spec.rb
> +      open_email(user.email, with_subject: 'Reset password instructions')
use i18n

2021-08-31 09:50 UTC, WoLkErSs commented on spec/features/authentication/restore_password_spec.rb
> +describe 'Forgot password' do
add tests for all cases

2021-09-02 09:16 UTC, WoLkErSs approved these changes
Fix please comment and merge

2021-09-02 09:16 UTC, WoLkErSs commented on spec/services/books_services/filters_spec.rb
> +        expect(described_class.new(params).call).to eq [Book.all.order(second_order), nil, second_filter]
move to subject

2021-09-02 09:16 UTC, WoLkErSs commented on spec/services/books_services/filters_spec.rb
> +    FactoryBot.create_list(:book, 5, categories: [category])
create less entities as it posible

2021-09-02 10:07 UTC, merged